#pragma once

#define COMMAND_QUEUE_SUPPORT_BIT_NONE     0x00
#define COMMAND_QUEUE_SUPPORT_BIT_GRAPHICS 0x01
#define COMMAND_QUEUE_SUPPORT_BIT_PRESENT  0x04
#define COMMAND_QUEUE_SUPPORT_BIT_COMPUTE  0x08
#define COMMAND_QUEUE_SUPPORT_BIT_COPY	   0x0F