#pragma once

enum class EventType
{
	EVENT_TYPE_NONE = 0x00,
	EVENT_TYPE_ERROR = 0x01,
	EVENT_TYPE_WINDOW_RESIZE = 0x02,
	EVENT_TYPE_KEY_DOWN = 0x03,
	EVENT_TYPE_KEY_UP = 0x04,
	EVENT_TYPE_RIGHT_BUTTON_DOWN = 0x05,
	EVENT_TYPE_RIGHT_BUTTON_UP = 0x06,
	EVENT_TYPE_LEFT_BUTTON_DOWN = 0x07,
	EVENT_TYPE_LEFT_BUTTON_UP = 0x08,
	EVENT_TYPE_MOUSE_MOVE = 0x09
};