#pragma once

enum class EventType
{
	EVENT_TYPE_NONE = 0x00,
	EVENT_TYPE_ERROR = 0x01,
	EVENT_TYPE_WINDOW_RESIZE = 0x02,
	EVENT_TYPE_KEY_DOWN = 0x03,
	EVENT_TYPE_KEY_UP = 0x04,
	EVENT_TYPE_RIGHT_CLICK_UP = 0x05,
	EVENT_TYPE_RIGHT_CLICK_DOWN = 0x06
};